// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-QPcP_SepAI2WoRK5qLqi0M_eaPX4HXw',
    appId: '1:686806256245:web:f014915e8a273e3e04063c',
    messagingSenderId: '686806256245',
    projectId: 'medicare-9d817',
    authDomain: 'medicare-9d817.firebaseapp.com',
    storageBucket: 'medicare-9d817.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAobWSmvkpqbbzVjTsOk_nezLlIpDni3Eg',
    appId: '1:686806256245:android:e39afdc38ad45d3004063c',
    messagingSenderId: '686806256245',
    projectId: 'medicare-9d817',
    storageBucket: 'medicare-9d817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5HbFm-o5mGfVw7jxd9ZME7w-SlqexMc',
    appId: '1:686806256245:ios:cec453d6cdad171804063c',
    messagingSenderId: '686806256245',
    projectId: 'medicare-9d817',
    storageBucket: 'medicare-9d817.firebasestorage.app',
    iosClientId: '686806256245-8l939p7vsfmspb9ad5pgcq7o6rtabovk.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK5HbFm-o5mGfVw7jxd9ZME7w-SlqexMc',
    appId: '1:686806256245:ios:cec453d6cdad171804063c',
    messagingSenderId: '686806256245',
    projectId: 'medicare-9d817',
    storageBucket: 'medicare-9d817.firebasestorage.app',
    iosClientId: '686806256245-8l939p7vsfmspb9ad5pgcq7o6rtabovk.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-QPcP_SepAI2WoRK5qLqi0M_eaPX4HXw',
    appId: '1:686806256245:web:1ef96c5b93bcae7304063c',
    messagingSenderId: '686806256245',
    projectId: 'medicare-9d817',
    authDomain: 'medicare-9d817.firebaseapp.com',
    storageBucket: 'medicare-9d817.firebasestorage.app',
  );
}
